remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme

title: Midnight theme
description: Midnight is a theme for GitHub Pages.
show_downloads: false
google_analytics: true
theme: jekyll-theme-midnight

title: Site by @bdeweesevans
description: my site!
