remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme

title: Midnight theme
description: Midnight is a theme for GitHub Pages.
show_downloads: 
google_analytics: 
theme: jekyll-theme-midnight

title: bdeweesevans
description: Benjamin DeWeese van Schooneveld
